//
// Created by Yao Guai on 16/9/17.
// Copyright (c) 2016 minions.jegarn.com. All rights reserved.
//

#import <Foundation/Foundation.h>


typedef NS_ENUM(NSInteger , MNErrorFaildCode) {
    FAIL_NETWORK = 3000,
    FAIL_SERVER_RESPONSE = 3001,
    SUCCESS = 0,
    FAIL_INTERNAL_NO_RESPONSE = 4000,
    FAIL_INTERNAL_NO_CODE = 4001,
    FAIL_INTERNAL_EXCEPTION = 4002,
    FAIL_INTERNAL_MULTI_SEND = 4003,
    FAIL_INTERNAL_MULTI_RESPONSE = 4004,
    FAIL_ACTION_NOT_REACHABLE = 4005,
    FAIL_REQUEST_METHOD = 4006,
    FAIL_PARAMETER_MISSING = 4007,
    FAIL_PARAMETER_TYPE = 4008,
    FAIL_OBJECT_NO_THIS_PROPERTY = 4009,
    FAIL_USER_UID_OR_NAME_NOT_EXISTS = 4010,
    FAIL_EMPTY_ACCOUNT = 5000,
    FAIL_EMPTY_PASSWORD = 5001,
    FAIL_WRONG_ACCOUNT_OR_PASSWORD = 5002,
    FAIL_LOGIN_TOO_FREQUENTLY = 5003,
    FAIL_USER_NAME_ALREADY_EXISTS = 5004,
    FAIL_DATABASE_ERROR = 5005,
    FAIL_USER_NOT_EXISTS = 5006,
    FAIL_PASSWORD_LENGTH = 5007,
    FAIL_INVALID_PASSWORD = 5008,
    FAIL_INVALID_IP = 5009,
    FAIL_USER_CREATE_TOO_FREQUENTLY = 5010,
    FAIL_USER_TOKEN_EXPIRE = 5011,
    FAIL_UPLOAD_EMPTY_FILE = 5012,
    FAIL_UPLOAD_FILE_TYPE = 5013,
    FAIL_UPLOAD_FILE_SIZE = 5014,
    FAIL_LOGIN_FAILED = 5015,
    FAIL_ROSTER_STATUS = 5016,
    FAIL_GROUP_ROSTER_NOT_EXISTS = 5017,
    FAIL_ROSTER_NOT_EXISTS = 5018,
    FAIL_MOVE_GROUP = 5019,
    FAIL_ROSTER_BLACK = 5020,
    FAIL_ROSTER_UNSUBSCRIBE = 5021,
    FAIL_MESSAGE_EMPTY = 5022,
    FAIL_OBJECT_NOT_FOUND = 5023,
    FAIL_MESSAGE_NOT_EXISTS = 5024,
    FAIL_GROUP_NAME_EMPTY = 5025,
    FAIL_GROUP_TYPE = 5026,
    FAIL_GROUP_NOT_EXISTS = 5027,
    FAIL_GROUP_USER_PERMISSION = 5028,
    FAIL_GROUP_USER_STATUS = 5029,
    FAIL_GROUP_USER_ALREADY_REQUEST = 5030,
    FAIL_GROUP_USER_ALREADY_MEMBER = 5031,
    FAIL_GROUP_USER_ALREADY_REFUSED = 5032,
    FAIL_GROUP_USER_NOT_EXISTS = 5033,
    FAIL_PERMISSION_DENY = 5034
};

@interface MNErrorCode : NSObject

+ (BOOL) isSuccess:(NSInteger) code;
+ (NSInteger) getNetworkErrorCode;
+ (NSString *) getMessage:(NSInteger) code;

@end