source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'minions' do
    pod 'AFNetworking', '~> 3.0'
    pod "UICKeyChainStore"
    pod 'YYModel'
    pod 'YYKeyboardManager'
    pod 'YYWebImage'
    pod "MPMessagePack"
end